#version 450

layout(local_size_x = 64) in;

layout(set = 0, binding = 0, std430) buffer Data {
   uint values[];
} data_buffer;

void main()
{
   uint row_width = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
   uint index = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * row_width;
   if (index < uint(data_buffer.values.length())) {
      uint seed = data_buffer.values[index];
      data_buffer.values[index] = seed * 3u + 7u;
   }
}
