ABI_VALUE(protocol.magic, VIOGPU_WDDM_ABI_MAGIC, 1347245636);
ABI_VALUE(protocol.version, VIOGPU_WDDM_ABI_VERSION, 0);
ABI_VALUE(capabilities.none, VIOGPU_WDDM_CAPABILITIES_NONE, 0);
ABI_VALUE(allocation.flag.primary, VIOGPU_WDDM_ALLOCATION_PRIMARY, 1);
ABI_VALUE(allocation.flag.cpu_visible, VIOGPU_WDDM_ALLOCATION_CPU_VISIBLE, 2);
ABI_VALUE(allocation.flag.native, VIOGPU_WDDM_ALLOCATION_NATIVE, 4);
ABI_VALUE(allocation.flag.gpu_read_only, VIOGPU_WDDM_ALLOCATION_GPU_READ_ONLY, 8);
ABI_VALUE(format.none, VIOGPU_WDDM_FORMAT_NONE, 0);
ABI_VALUE(format.b8g8r8a8_unorm, VIOGPU_WDDM_FORMAT_B8G8R8A8_UNORM, 1);
ABI_VALUE(format.b8g8r8x8_unorm, VIOGPU_WDDM_FORMAT_B8G8R8X8_UNORM, 2);
ABI_VALUE(context.flags.none, VIOGPU_WDDM_CONTEXT_FLAGS_NONE, 0);
ABI_VALUE(escape.opcode.get_context_info, VIOGPU_WDDM_ESCAPE_GET_CONTEXT_INFO, 1);
ABI_VALUE(escape.flags.none, VIOGPU_WDDM_ESCAPE_FLAGS_NONE, 0);
ABI_VALUE(render.opcode.native_submit, VIOGPU_WDDM_RENDER_NATIVE_SUBMIT, 1);
ABI_VALUE(render.flags.none, VIOGPU_WDDM_RENDER_FLAGS_NONE, 0);
ABI_VALUE(reference.flag.read, VIOGPU_WDDM_REFERENCE_READ, 1);
ABI_VALUE(reference.flag.write, VIOGPU_WDDM_REFERENCE_WRITE, 2);
ABI_SIZE(size.uint32, VIOGPU_WDDM_UINT32, 4);
ABI_SIZE(size.uint64, VIOGPU_WDDM_UINT64, 8);

ABI_SIZE(size.header, VIOGPU_WDDM_ABI_HEADER, 16);
ABI_OFFSET(offset.header.magic, VIOGPU_WDDM_ABI_HEADER, Magic, 0);
ABI_OFFSET(offset.header.version, VIOGPU_WDDM_ABI_HEADER, Version, 4);
ABI_OFFSET(offset.header.size, VIOGPU_WDDM_ABI_HEADER, Size, 8);
ABI_OFFSET(offset.header.reserved, VIOGPU_WDDM_ABI_HEADER, Reserved, 12);

ABI_SIZE(size.adapter_info, VIOGPU_WDDM_ADAPTER_INFO, 128);
ABI_OFFSET(offset.adapter_info.header, VIOGPU_WDDM_ADAPTER_INFO, Header, 0);
ABI_OFFSET(offset.adapter_info.capabilities, VIOGPU_WDDM_ADAPTER_INFO, Capabilities, 16);
ABI_OFFSET(offset.adapter_info.reset_generation, VIOGPU_WDDM_ADAPTER_INFO, ResetGeneration, 24);
ABI_OFFSET(offset.adapter_info.msm_major_version, VIOGPU_WDDM_ADAPTER_INFO, MsmMajorVersion, 32);
ABI_OFFSET(offset.adapter_info.msm_minor_version, VIOGPU_WDDM_ADAPTER_INFO, MsmMinorVersion, 36);
ABI_OFFSET(offset.adapter_info.msm_patch_version, VIOGPU_WDDM_ADAPTER_INFO, MsmPatchVersion, 40);
ABI_OFFSET(offset.adapter_info.gpu_id, VIOGPU_WDDM_ADAPTER_INFO, GpuId, 44);
ABI_OFFSET(offset.adapter_info.chip_id, VIOGPU_WDDM_ADAPTER_INFO, ChipId, 48);
ABI_OFFSET(offset.adapter_info.gmem_size, VIOGPU_WDDM_ADAPTER_INFO, GmemSize, 56);
ABI_OFFSET(offset.adapter_info.priority_count, VIOGPU_WDDM_ADAPTER_INFO, PriorityCount, 60);
ABI_OFFSET(offset.adapter_info.gmem_base, VIOGPU_WDDM_ADAPTER_INFO, GmemBase, 64);
ABI_OFFSET(offset.adapter_info.highest_bank_bit, VIOGPU_WDDM_ADAPTER_INFO, HighestBankBit, 72);
ABI_OFFSET(offset.adapter_info.has_cached_coherent, VIOGPU_WDDM_ADAPTER_INFO, HasCachedCoherentMemory, 76);
ABI_OFFSET(offset.adapter_info.ubwc_swizzle, VIOGPU_WDDM_ADAPTER_INFO, UbwcSwizzle, 80);
ABI_OFFSET(offset.adapter_info.macrotile_mode, VIOGPU_WDDM_ADAPTER_INFO, MacrotileMode, 88);
ABI_OFFSET(offset.adapter_info.uche_trap_base, VIOGPU_WDDM_ADAPTER_INFO, UcheTrapBase, 96);
ABI_OFFSET(offset.adapter_info.has_ray_tracing, VIOGPU_WDDM_ADAPTER_INFO, HasRayTracing, 104);
ABI_OFFSET(offset.adapter_info.max_frequency, VIOGPU_WDDM_ADAPTER_INFO, MaxFrequency, 108);
ABI_OFFSET(offset.adapter_info.reserved, VIOGPU_WDDM_ADAPTER_INFO, Reserved, 112);

ABI_SIZE(size.allocation_info, VIOGPU_WDDM_ALLOCATION_INFO, 80);
ABI_OFFSET(offset.allocation_info.header, VIOGPU_WDDM_ALLOCATION_INFO, Header, 0);
ABI_OFFSET(offset.allocation_info.size, VIOGPU_WDDM_ALLOCATION_INFO, Size, 16);
ABI_OFFSET(offset.allocation_info.alignment, VIOGPU_WDDM_ALLOCATION_INFO, Alignment, 24);
ABI_OFFSET(offset.allocation_info.requested_iova, VIOGPU_WDDM_ALLOCATION_INFO, RequestedIova, 32);
ABI_OFFSET(offset.allocation_info.expected_reset_generation, VIOGPU_WDDM_ALLOCATION_INFO, ExpectedResetGeneration, 40);
ABI_OFFSET(offset.allocation_info.flags, VIOGPU_WDDM_ALLOCATION_INFO, Flags, 48);
ABI_OFFSET(offset.allocation_info.format, VIOGPU_WDDM_ALLOCATION_INFO, Format, 52);
ABI_OFFSET(offset.allocation_info.width, VIOGPU_WDDM_ALLOCATION_INFO, Width, 56);
ABI_OFFSET(offset.allocation_info.height, VIOGPU_WDDM_ALLOCATION_INFO, Height, 60);
ABI_OFFSET(offset.allocation_info.pitch, VIOGPU_WDDM_ALLOCATION_INFO, Pitch, 64);
ABI_OFFSET(offset.allocation_info.refresh_numerator, VIOGPU_WDDM_ALLOCATION_INFO, RefreshRateNumerator, 68);
ABI_OFFSET(offset.allocation_info.refresh_denominator, VIOGPU_WDDM_ALLOCATION_INFO, RefreshRateDenominator, 72);
ABI_OFFSET(offset.allocation_info.context_id, VIOGPU_WDDM_ALLOCATION_INFO, ContextId, 76);

ABI_SIZE(size.context_create, VIOGPU_WDDM_CONTEXT_CREATE, 32);
ABI_OFFSET(offset.context_create.header, VIOGPU_WDDM_CONTEXT_CREATE, Header, 0);
ABI_OFFSET(offset.context_create.expected_reset_generation, VIOGPU_WDDM_CONTEXT_CREATE, ExpectedResetGeneration, 16);
ABI_OFFSET(offset.context_create.flags, VIOGPU_WDDM_CONTEXT_CREATE, Flags, 24);
ABI_OFFSET(offset.context_create.reserved, VIOGPU_WDDM_CONTEXT_CREATE, Reserved, 28);

ABI_SIZE(size.context_info, VIOGPU_WDDM_CONTEXT_INFO, 64);
ABI_OFFSET(offset.context_info.header, VIOGPU_WDDM_CONTEXT_INFO, Header, 0);
ABI_OFFSET(offset.context_info.opcode, VIOGPU_WDDM_CONTEXT_INFO, Opcode, 16);
ABI_OFFSET(offset.context_info.flags, VIOGPU_WDDM_CONTEXT_INFO, Flags, 20);
ABI_OFFSET(offset.context_info.expected_reset_generation, VIOGPU_WDDM_CONTEXT_INFO, ExpectedResetGeneration, 24);
ABI_OFFSET(offset.context_info.va_start, VIOGPU_WDDM_CONTEXT_INFO, VaStart, 32);
ABI_OFFSET(offset.context_info.va_size, VIOGPU_WDDM_CONTEXT_INFO, VaSize, 40);
ABI_OFFSET(offset.context_info.reset_generation, VIOGPU_WDDM_CONTEXT_INFO, ResetGeneration, 48);
ABI_OFFSET(offset.context_info.context_id, VIOGPU_WDDM_CONTEXT_INFO, ContextId, 56);
ABI_OFFSET(offset.context_info.submit_queue_id, VIOGPU_WDDM_CONTEXT_INFO, SubmitQueueId, 60);

ABI_SIZE(size.render_command, VIOGPU_WDDM_RENDER_COMMAND, 64);
ABI_OFFSET(offset.render_command.header, VIOGPU_WDDM_RENDER_COMMAND, Header, 0);
ABI_OFFSET(offset.render_command.opcode, VIOGPU_WDDM_RENDER_COMMAND, Opcode, 16);
ABI_OFFSET(offset.render_command.flags, VIOGPU_WDDM_RENDER_COMMAND, Flags, 20);
ABI_OFFSET(offset.render_command.expected_reset_generation, VIOGPU_WDDM_RENDER_COMMAND, ExpectedResetGeneration, 24);
ABI_OFFSET(offset.render_command.references_offset, VIOGPU_WDDM_RENDER_COMMAND, AllocationReferencesOffset, 32);
ABI_OFFSET(offset.render_command.reference_count, VIOGPU_WDDM_RENDER_COMMAND, AllocationReferenceCount, 36);
ABI_OFFSET(offset.render_command.command_stream_offset, VIOGPU_WDDM_RENDER_COMMAND, CommandStreamOffset, 40);
ABI_OFFSET(offset.render_command.command_stream_size, VIOGPU_WDDM_RENDER_COMMAND, CommandStreamSize, 44);
ABI_OFFSET(offset.render_command.reserved, VIOGPU_WDDM_RENDER_COMMAND, Reserved, 48);

ABI_SIZE(size.allocation_reference, VIOGPU_WDDM_ALLOCATION_REFERENCE, 32);
ABI_OFFSET(offset.allocation_reference.allocation_index, VIOGPU_WDDM_ALLOCATION_REFERENCE, AllocationIndex, 0);
ABI_OFFSET(offset.allocation_reference.flags, VIOGPU_WDDM_ALLOCATION_REFERENCE, Flags, 4);
ABI_OFFSET(offset.allocation_reference.allocation_offset, VIOGPU_WDDM_ALLOCATION_REFERENCE, AllocationOffset, 8);
ABI_OFFSET(offset.allocation_reference.length, VIOGPU_WDDM_ALLOCATION_REFERENCE, Length, 16);
ABI_OFFSET(offset.allocation_reference.patch_offset, VIOGPU_WDDM_ALLOCATION_REFERENCE, PatchOffset, 24);
ABI_OFFSET(offset.allocation_reference.reserved, VIOGPU_WDDM_ALLOCATION_REFERENCE, Reserved, 28);
